
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ecommerce-app_development

test:
  <<: *default
  database: ecommerce-app_test

production:
  database: ecommerce-app-production
  adapter: postgresql
  encoding: unicode
  pool: 5
